### ISSUE TITLE
[ BUG ] 예정된 수업 > ‘상태없음’으로 되어있음

### ISSUE THREAD

**Issue by eunbeann** [Gwasuwon-shot/Tutice_Client#430]
# 🐛 버그 수정

## 🔎 버그 설명

- [학부모뷰] - [예정된 수업 > ‘상태없음’으로 되어있음]
[세부 내용 노션](https://www.notion.so/class-cha/e937d792df684083b6a7473b7f027522?pvs=4)

## ✅ 해결 방안

상태없음 대신 ‘수업예정’ 이라고 워딩을 바꾸기

**Comment by hae2ni** [comment]
요거 현재 혹시 api 연결 되어 있나요? 명세서에서 아무리 찾아도 못 찾겠어서리,,

**Comment by eunbeann** [comment]
@hae2ni 이거 연결되어 있는거 워딩 수정만 하면 되는거엿오요!!! 코어 타임때 서버에서 수정 해줘서 제가 반영해두었습니다앙
