### ISSUE TITLE
[ FEAT ] GA 붙이기

### ISSUE THREAD

**Issue by eunbeann** [Gwasuwon-shot/Tutice_Client#437]
# ✨ 새 기능 요청

## 🚀 목표

- Google Analytics를 서비스에 부착합니당

## 📝 상세 설명

- 기획 선생님의 구체적인 논의 후에 진행되어야 하는 작업입니다! - [노션 링크](https://www.notion.so/class-cha/GA-aaca711f28294e6fa19f7384418900d4)

- [참고 링크](https://velog.io/@hnnynh/React%EC%97%90-GA4-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0)
- [참고 링크2](https://velog.io/@jeongbeen2/React-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90-GA-%EB%8F%84%EC%9E%85%ED%95%98%EA%B8%B0)

## ✅ 체크리스트
- [x] GA 계정 확인
- [ ] 라이브러리 설치
- [ ] 필요 버튼에 부착
- [ ] 블로깅해두면 좋을 듯!

**Comment by hae2ni** [comment]
확인했습니당:)

**Comment by hae2ni** [comment]
ㅎ,,,,,,, 몇 시간 동안 라이브러리 설치에만 에러가 떠서,,,,,,,,,,,, 
해결 중인데 이게 패키지 설치까지 포함되어 있어서,,, 하나 고치는데 한참인,,,상황입니다,, 
@eunbeann
