### ISSUE TITLE
[ BUG ] 회차당 과외비 입력 백스페이스

### ISSUE THREAD

**Issue by hae2ni** [Gwasuwon-shot/Tutice_Client#471]
# 🐛 버그 수정

## 🔎 버그 설명

- [정기 수업 등록] - [백스페이스 안됨]

## 📈 재현 방법

1. 
2. 
3.

**Comment by eunbeann** [comment]
https://github.com/Gwasuwon-shot/Tutice_Client/commit/3815a0f5f809d0e459b852637b27b1ccc1a27759

헉 이거 해결했어요!

[이거 확인](https://www.notion.so/class-cha/5-11-QA-db5cce5498ac409aa5ac976bde0fbd0d)이 페이지에 QA 리스트랑 완료된 QA 같이 있어요!!

**Comment by eunbeann** [comment]
상기 이유로 close 하겠습니다아
